let db = [
	[
		{
			key: 'Tables_in_new_milkgate_general',
			m: {
				Tables_in_new_milkgate_general: 'aggregate_versions',
			},
			createStatement: [
				{
					Table: 'aggregate_versions',
					'Create Table':
						'CREATE TABLE `aggregate_versions` (\n  `aggregate_id` varchar(64) COLLATE utf8_unicode_ci NOT NULL,\n  `latest_version` int(11) NOT NULL,\n  `created_at` bigint(13) DEFAULT NULL,\n  `updated_at` bigint(13) DEFAULT NULL,\n  PRIMARY KEY (`aggregate_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
				},
			],
			describe: [
				{
					Field: 'aggregate_id',
					Type: 'varchar(64)',
					Null: 'NO',
					Key: 'PRI',
					Default: null,
					Extra: '',
				},
				{
					Field: 'latest_version',
					Type: 'int(11)',
					Null: 'NO',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'created_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'updated_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
			],
		},
	],
	[
		{
			key: 'Tables_in_new_milkgate_general',
			m: {
				Tables_in_new_milkgate_general: 'credit_cards',
			},
			createStatement: [
				{
					Table: 'credit_cards',
					'Create Table':
						'CREATE TABLE `credit_cards` (\n  `id` varchar(60) COLLATE utf8_unicode_ci NOT NULL,\n  `version` int(11) DEFAULT NULL,\n  `zip_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `province` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `country_code` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_number_masked` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_first6` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_last4` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_expiry_month` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_expiry_year` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `created_at` bigint(13) DEFAULT NULL,\n  `account_id` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `domain_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `customer_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `updated_at` bigint(13) DEFAULT NULL,\n  `client_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `deactivated_at` bigint(13) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `credit_cards_account_id_index` (`account_id`),\n  KEY `credit_cards_version_index` (`version`),\n  KEY `credit_cards_created_at_index` (`created_at`),\n  KEY `credit_cards_customer_id_index` (`customer_id`),\n  KEY `credit_cards_updated_at_index` (`updated_at`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
				},
			],
			describe: [
				{
					Field: 'id',
					Type: 'varchar(60)',
					Null: 'NO',
					Key: 'PRI',
					Default: null,
					Extra: '',
				},
				{
					Field: 'version',
					Type: 'int(11)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'zip_code',
					Type: 'varchar(10)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'province',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'country_code',
					Type: 'varchar(3)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_number_masked',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_first6',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_last4',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_expiry_month',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_expiry_year',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'created_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'account_id',
					Type: 'varchar(60)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'domain_name',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'customer_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'updated_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'client_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'deactivated_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
			],
		},
	],
	[
		{
			key: 'Tables_in_new_milkgate_general',
			m: {
				Tables_in_new_milkgate_general: 'event_store_rm',
			},
			createStatement: [
				{
					Table: 'event_store_rm',
					'Create Table':
						'CREATE TABLE `event_store_rm` (\n  `id` bigint(20) NOT NULL AUTO_INCREMENT,\n  `payload` longtext COLLATE utf8_unicode_ci,\n  `aggregate_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `sequence_id` int(10) DEFAULT NULL,\n  `created_at` bigint(13) DEFAULT NULL,\n  `inserted_at_rm` bigint(13) DEFAULT NULL,\n  `inserted_at_wm` bigint(13) DEFAULT NULL,\n  `aggregate_type` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `event_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `account_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `event_hash` varchar(70) COLLATE utf8_unicode_ci DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `event_store_rm_account_id_index` (`account_id`),\n  KEY `event_store_rm_event_hash_index` (`event_hash`),\n  KEY `event_store_rm_aggregate_id_index` (`aggregate_id`)\n) ENGINE=InnoDB AUTO_INCREMENT=50019933 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
				},
			],
			describe: [
				{
					Field: 'id',
					Type: 'bigint(20)',
					Null: 'NO',
					Key: 'PRI',
					Default: null,
					Extra: 'auto_increment',
				},
				{
					Field: 'payload',
					Type: 'longtext',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'aggregate_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'sequence_id',
					Type: 'int(10)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'created_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'inserted_at_rm',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'inserted_at_wm',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'aggregate_type',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'event_name',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'account_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'event_hash',
					Type: 'varchar(70)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
			],
		},
	],
	[
		{
			key: 'Tables_in_new_milkgate_general',
			m: {
				Tables_in_new_milkgate_general: 'transaction_details',
			},
			createStatement: [
				{
					Table: 'transaction_details',
					'Create Table':
						'CREATE TABLE `transaction_details` (\n  `id` varchar(64) COLLATE utf8_unicode_ci NOT NULL,\n  `type` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `status` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `amount` decimal(10,2) DEFAULT NULL,\n  `currency` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `converted_amount` decimal(10,2) DEFAULT NULL,\n  `converted_currency` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `created_at` bigint(13) DEFAULT NULL,\n  `source_reference_trans_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `source_reference_meta` longtext COLLATE utf8_unicode_ci,\n  `card_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `processor_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `account_id` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `domain_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `client_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `transaction_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `processor_transaction_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `processor_auth_code` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `processor_transaction_meta` longtext COLLATE utf8_unicode_ci,\n  `processor_message` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `processor_status_code` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `processor_cvv_result` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `customer_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_number_masked` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `customer_country` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_last_4_digits` varchar(4) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_first_6_digits` varchar(6) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `version` int(11) DEFAULT NULL,\n  `master_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `updated_at` bigint(13) DEFAULT NULL,\n  `source_reference_customer_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `transaction_details_account_id_index` (`account_id`),\n  KEY `transaction_details_status_index` (`status`),\n  KEY `transaction_details_transaction_id` (`transaction_id`),\n  KEY `transaction_details_version_index` (`version`),\n  KEY `transaction_details_master_id_index` (`master_id`),\n  KEY `transaction_details_customer_id_index` (`customer_id`),\n  KEY `transaction_details_source_reference_trans_id_index` (`source_reference_trans_id`),\n  KEY `transaction_details_created_at_index` (`created_at`),\n  KEY `transaction_details_updated_at_index` (`updated_at`),\n  KEY `transaction_details_trans_id_version_account_index` (`account_id`,`transaction_id`,`version`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
				},
			],
			describe: [
				{
					Field: 'id',
					Type: 'varchar(64)',
					Null: 'NO',
					Key: 'PRI',
					Default: null,
					Extra: '',
				},
				{
					Field: 'type',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'status',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'currency',
					Type: 'varchar(3)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'converted_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'converted_currency',
					Type: 'varchar(3)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'created_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'source_reference_trans_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'source_reference_meta',
					Type: 'longtext',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'card_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'account_id',
					Type: 'varchar(60)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'domain_name',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'client_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'transaction_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_transaction_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_auth_code',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_transaction_meta',
					Type: 'longtext',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_message',
					Type: 'varchar(255)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_status_code',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'processor_cvv_result',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'customer_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_number_masked',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'customer_country',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_last_4_digits',
					Type: 'varchar(4)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_first_6_digits',
					Type: 'varchar(6)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'version',
					Type: 'int(11)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'master_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'updated_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'source_reference_customer_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
			],
		},
	],
	[
		{
			key: 'Tables_in_new_milkgate_general',
			m: {
				Tables_in_new_milkgate_general: 'transactions',
			},
			createStatement: [
				{
					Table: 'transactions',
					'Create Table':
						'CREATE TABLE `transactions` (\n  `id` varchar(64) COLLATE utf8_unicode_ci NOT NULL,\n  `type` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `status` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `amount` decimal(10,2) DEFAULT NULL,\n  `currency` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `converted_amount` decimal(10,2) DEFAULT NULL,\n  `converted_currency` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `auth_amount` decimal(10,2) DEFAULT NULL,\n  `sale_amount` decimal(10,2) DEFAULT NULL,\n  `capture_amount` decimal(10,2) DEFAULT NULL,\n  `void_amount` decimal(10,2) DEFAULT NULL,\n  `refund_amount` decimal(10,2) DEFAULT NULL,\n  `created_at` bigint(13) DEFAULT NULL,\n  `card_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `account_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `domain_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `customer_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `customer_country` varchar(2) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `province` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `zip_code` varchar(10) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_last_4_digits` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_first_6_digits` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `credit_card_number_masked` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `version` int(11) DEFAULT NULL,\n  `updated_at` bigint(13) DEFAULT NULL,\n  `source_reference_customer_id` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,\n  `client_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `transactions_account_id_index` (`account_id`),\n  KEY `transactions_status_index` (`status`),\n  KEY `transactions_version_index` (`version`),\n  KEY `transactions_customer_id_index` (`customer_id`),\n  KEY `transactions_created_at_index` (`created_at`),\n  KEY `transactions_updated_at_index1` (`account_id`,`updated_at`),\n  KEY `transactions_id_version_index` (`id`,`version`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci',
				},
			],
			describe: [
				{
					Field: 'id',
					Type: 'varchar(64)',
					Null: 'NO',
					Key: 'PRI',
					Default: null,
					Extra: '',
				},
				{
					Field: 'type',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'status',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'currency',
					Type: 'varchar(3)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'converted_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'converted_currency',
					Type: 'varchar(3)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'auth_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'sale_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'capture_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'void_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'refund_amount',
					Type: 'decimal(10,2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'created_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'card_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'account_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'domain_name',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'customer_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'customer_country',
					Type: 'varchar(2)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'province',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'zip_code',
					Type: 'varchar(10)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_last_4_digits',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_first_6_digits',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'credit_card_number_masked',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'version',
					Type: 'int(11)',
					Null: 'YES',
					Key: 'MUL',
					Default: null,
					Extra: '',
				},
				{
					Field: 'updated_at',
					Type: 'bigint(13)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'source_reference_customer_id',
					Type: 'varchar(64)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
				{
					Field: 'client_id',
					Type: 'varchar(45)',
					Null: 'YES',
					Key: '',
					Default: null,
					Extra: '',
				},
			],
		},
	],
];