CREATE table transactions_events(
    `id` int NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    `timestamp` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `transaction_id` varchar(45) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pk` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
    `sk` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
    `sub_transaction_type` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL,
    `organisation_id` varchar(3) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `amount` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `type` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `status` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `entity_type` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `created_date` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `partition` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `gsi1pk` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `gsi1sk` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `card_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_cvv_result` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_auth_code` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_status_code` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_message` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_transactionMeta` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `processor_transactionId` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `sale_token_used` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `token_info` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
